import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("investigation reference pages are source-driven and routed", async () => {
  const rules = await readFile(new URL("../src/rules.ts", import.meta.url), "utf8");
  const data = await readFile(new URL("../src/investigation-data.ts", import.meta.url), "utf8");
  const api = await readFile(new URL("../api/rules-ai.ts", import.meta.url), "utf8");
  const server = await readFile(new URL("../server/rules-ai.ts", import.meta.url), "utf8");
  const vercel = await readFile(new URL("../vercel.json", import.meta.url), "utf8");
  assert.match(rules, /renderInvestigationHome/);
  assert.match(rules, /renderAppendixPage/);
  assert.match(rules, /renderFaqPage/);
  assert.match(rules, /renderWikiPage/);
  assert.match(rules, /rules-ai-form/);
  assert.match(rules, /问你想问的，<br \/>工会总有答案/);
  assert.match(rules, /输入任意问题，获得规则解答或者指引/);
  assert.match(rules, /rules-portal-card/);
  assert.match(rules, /investigation-delve-boardgame\/rules/);
  assert.match(rules, /type RulesRoute = "home"/);
  assert.match(rules, /3-游戏配件-1\.png/);
  assert.match(rules, /13-游戏配件-11\.png/);
  assert.match(data, /parseCsv/);
  assert.match(data, /调查员\.csv\?raw/);
  assert.match(data, /辅助卡牌\.csv\?raw/);
  assert.match(rules, /allInvestigationCards/);
  assert.match(vercel, /investigation-delve-boardgame\/:path\*/);
  assert.match(rules, /aria-label="选择语言"/);
  assert.doesNotMatch(rules, /文字选择/);
  assert.match(api, /IncomingMessage/);
  assert.match(api, /handleRulesAiRequest/);
  assert.match(server, /OPENROUTER_API_KEY/);
  assert.match(server, /nvidia\/nemotron-3-super-120b-a12b:free/);
  assert.match(server, /通常只回答 1—3 句/);
  assert.match(server, /最多引用一句/);
  assert.match(server, /每项单独换行/);
  assert.match(server, /max_tokens: 768/);
  assert.match(server, /reasoning: \{ effort: "none", exclude: true \}/);
  assert.doesNotMatch(server, /provider\.name === "OpenRouter" \? \{ reasoning:/);
  assert.match(server, /<answer>/);
  assert.match(server, /reasoning_content/);
  assert.match(server, /快速游玩流程/);
  assert.match(server, /rules#quick-start/);
  assert.match(server, /卡牌 Wiki/);
  assert.match(server, /investigation-delve-boardgame\/wiki/);
  assert.match(server, /src\/data\/investigation\/调查员\.csv/);
  assert.match(server, /stream: true/);
  assert.match(vercel, /api\/rules-ai\.ts/);
});

test("rulebook teaching text keeps canonical wording and font roles", async () => {
  const rules = await readFile(new URL("../src/rules.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
  const rulesStyles = await readFile(new URL("../src/rules.css", import.meta.url), "utf8");
  assert.match(rules, /即使你已经玩过很多次《调查 : 深入》/);
  assert.match(rules, /「操作阶段」分为以下3个步骤/);
  assert.match(rules, /其他队伍的所有「调查员」都「陷入疯狂」时/);
  assert.match(rules, /class="rules-original"/);
  assert.match(rules, /class="rules-dek rules-editorial">翻开情报，真相就离你更近一步/);
  assert.match(styles, /SourceHanSansSC-Regular\.otf/);
  assert.match(styles, /SourceHanSerifSC-Regular\.otf/);
  assert.match(styles, /--font-rules-display: "Times New Roman"/);
  assert.match(rulesStyles, /\.rules-page \{ font-family: var\(--font-rules-display\); \}/);
  assert.match(rulesStyles, /\.rules-page \.rules-original \{ font-family: var\(--font-rules-original\); \}/);
  assert.match(rulesStyles, /\.rules-page \.rules-editorial \{ font-family: var\(--font-rules-display\); \}/);
  assert.match(rulesStyles, /\.rules-ai-thinking/);
  assert.match(rulesStyles, /\.rules-ai-response a/);
  assert.match(rulesStyles, /white-space: pre-wrap/);
  assert.match(rulesStyles, /\.rules-header-meta a \{[^}]*line-height: 15px/);
  assert.match(rulesStyles, /\.rules-page \.rules-content h2, \.rules-page \.rules-content h3 \{ font-family: var\(--font-rules-display\); \}/);
});
