import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("build emits the native Vite site", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  assert.match(html, /FreshLi4/);
  assert.match(html, /<script type="module"/);
  await access(new URL("../dist/assets/", import.meta.url));
});

test("source keeps the dynamic visual-content convention", async () => {
  const source = await readFile(new URL("../src/main.ts", import.meta.url), "utf8");
  assert.match(source, /import\.meta\.glob\("\/asset\/\*\/visual-content\/\*"/);
  assert.match(source, /videoExtensions/);
  assert.match(source, /setTimeout\(\(\) => show\(current \+ 1\), 3000\)/);
  assert.match(source, /class="games-flow"/);
  assert.match(source, /class="game-section/);
  assert.match(source, /data-site-nav="studio"/);
  assert.match(source, /data-project-tab/);
  assert.match(source, /aria-orientation="vertical"/);
  assert.doesNotMatch(source, /data-project-direction/);
  assert.doesNotMatch(source, /projectAutoplayDelay|projectVisibilityObserver|data-game-slide/);

  const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
  assert.match(styles, /\.game-section \{ min-height:100svh/);
  assert.match(styles, /position:fixed; z-index:50; top:50%; left:var\(--page-pad\)/);
  assert.match(styles, /will-change:opacity; transition:opacity \.55s ease/);
  assert.match(styles, /\.games-controls\.is-idle \{ opacity:0; \}/);
  assert.match(styles, /flex-direction:column; justify-content:flex-start; align-items:flex-start/);
  assert.match(source, /navigationIdleTimer = window\.setTimeout\([\s\S]*?, 1000\);/);
  assert.match(source, /navigationHoverTarget\?\.addEventListener\("mouseenter", pauseNavigationIdleTimer\)/);
  assert.match(source, /navigationHoverTarget\?\.addEventListener\("mouseleave", keepNavigationVisible\)/);
  assert.doesNotMatch(styles, /games-showcase|games-sticky|games-slides|game-slide|is-project-snapping/);
});

test("source exposes the investigation rulebook as a second-level page", async () => {
  const source = await readFile(new URL("../src/main.ts", import.meta.url), "utf8");
  const rules = await readFile(new URL("../src/rules.ts", import.meta.url), "utf8");
  const rulesStyles = await readFile(new URL("../src/rules.css", import.meta.url), "utf8");
  const aiServer = await readFile(new URL("../server/rules-ai.ts", import.meta.url), "utf8");
  assert.match(source, /\/investigation-delve-boardgame/);
  assert.match(source, /project-rules-link.*href="\/investigation-delve-boardgame"/);
  assert.match(source, /了解详情/);
  assert.match(rules, /class="rules-brand" href="\/investigation-delve-boardgame"/);
  assert.match(rules, /class="rules-brand-logo" src="\/investigation-delve-logo\.png"/);
  assert.match(rulesStyles, /\.rules-brand-logo \{[^}]*object-fit: contain/);
  assert.match(rules, /const investigationVisualFiles = import\.meta\.glob\("\/asset\/investigation-delve\/visual-content\/\*"/);
  assert.match(rules, /investigationVisual\("3-游戏配件-1\.png"\)/);
  assert.match(rules, /bootRulesPage/);
  assert.match(rules, /规则指引书/);
  assert.match(rules, /调查附录/);
  assert.match(rules, /FAQ/);
  assert.match(rules, /class="rules-route-nav"[\s\S]*class="rules-route-tools"/);
  assert.match(rules, /class="rules-route-menu-toggle"[^>]*aria-controls="rules-route-menu-panel"/);
  assert.match(rules, /const setRouteMenuOpen = \(isOpen: boolean\)/);
  assert.match(rules, /const rulesToc = \(className = "rules-toc"\)/);
  assert.match(rules, /rulesToc\("rules-toc rules-toc-mobile"\)/);
  assert.match(rules, /class="rules-page rules-rulebook"/);
  assert.doesNotMatch(rules, /<section class="rules-hero"/);
  assert.match(rules, /const mobileViewport = window\.matchMedia\("\(max-width: 640px\)"\)/);
  assert.match(rules, /rulebookHeader\.classList\.add\("is-scroll-hidden"\)/);
  assert.match(rules, /rules-subpage-\$\{active\}/);
  assert.match(rules, /所有卡牌，<br \/>一览无遗。/);
  assert.match(rules, /定义的开始，<br \/>就是智慧的开始。/);
  assert.match(rules, /明辨过往，<br \/>未雨绸缪。/);
  assert.match(rules, /这里收录《调查深入》的全部卡牌。/);
  assert.match(rulesStyles, /\.rules-route-menu-toggle \{ display: none/);
  assert.match(rulesStyles, /\.rules-route-nav\.is-open \.rules-route-menu-panel \{ display: flex/);
  assert.match(rulesStyles, /\.rules-rulebook \.rules-sidebar \{ position: sticky; top: 28px; \}/);
  assert.match(rulesStyles, /\.rules-toc-mobile \{ display: none; \}/);
  assert.match(rulesStyles, /\.rules-rulebook \.rules-header\.is-scroll-hidden \{ transform: translateY\(-100%\); \}/);
  assert.match(rulesStyles, /\.rules-rulebook \.rules-sidebar \.rules-toc \{ display: none; \}/);
  assert.match(rulesStyles, /\.rules-route-nav\.is-open \.rules-toc-mobile \{ display: grid; \}/);
  assert.match(rulesStyles, /\.rules-subpage-wiki \.rules-subpage-hero \{ grid-template-columns: 1fr;/);
  assert.match(rulesStyles, /\.rules-subpage-wiki \.rules-subpage-hero h1 \{ max-width: none;[^}]*white-space: nowrap;/);
  assert.match(rulesStyles, /\.rules-home-visual img \{ position: absolute; inset: 0;/);
  assert.match(rulesStyles, /\.rules-home-visual \{ min-height: 0; aspect-ratio: 1463 \/ 1003; \}/);
  assert.match(rulesStyles, /\.home-visual-note \{ display: none; \}/);
  assert.doesNotMatch(rules, /rules-header-meta/);
  assert.match(rules, /一款支持 2–6 人游玩的非直接对战美式桌游/);
  assert.match(rules, /问你想问的，<br \/>工会总有答案/);
  assert.match(rulesStyles, /\.rules-ai h2 \{ white-space: nowrap; \}/);
  assert.match(rulesStyles, /@media \(max-width: 640px\) \{ \.rules-ai h2 \{ font-size: clamp\(34px, 9vw, 55px\); \} \}/);
  assert.match(rules, /responseLine\.className = "rules-ai-response-line"/);
  assert.match(rules, /responseLine\.append\(thinking, paragraph\)/);
  assert.match(rulesStyles, /\.rules-ai-response-line \{ display: flex; align-items: center; gap: 12px; margin-top: 15px; \}/);
  assert.match(rulesStyles, /\.rules-ai-response-line \.rules-ai-response \{ flex: 1 1 auto; min-width: 0; margin-top: 0; margin-bottom: 0; \}/);
  assert.match(rulesStyles, /\.rules-ai-response a \{ color: var\(--rules-brass\);/);
  assert.match(rulesStyles, /\.rules-ai-form button \{[^}]*white-space: nowrap;/);
  assert.match(rulesStyles, /\.rules-ai-form > div \{ grid-template-columns: minmax\(0, 1fr\) auto; \}/);
  assert.match(rulesStyles, /\.rules-ai-thinking \{ position: relative; flex: 0 0 1\.75em; width: 1\.75em; height: 1\.75em; margin-top: 0;/);
  assert.match(rulesStyles, /\.rules-ai-thinking i \{ position: absolute; top: 50%; left: 50%; width: \.3125em; height: \.3125em; margin: -\.15625em 0 0 -\.15625em;/);
  assert.match(rulesStyles, /transform: rotate\(calc\(var\(--rules-ai-orb-index\) \* 72deg\)\) translateY\(-\.5em\); transform-origin: center;/);
  assert.match(rules, /const faqGroup = \(label: string, details: string\)/);
  assert.doesNotMatch(rules, /先解决最常见的行动问题。/);
  assert.doesNotMatch(rules, /仿生人与 SAN。/);
  assert.match(rules, /const summaryRole = card\.category === "investigator"/);
  assert.match(rules, /class="wiki-card-heading"/);
  assert.match(rules, /class="wiki-card-role"/);
  assert.doesNotMatch(rules, /wiki-card-index/);
  assert.match(rulesStyles, /\.wiki-card details > summary \{ grid-template-columns: minmax\(0, 1fr\) auto 20px; \}/);
  assert.match(rulesStyles, /\.wiki-card-strategy \.wiki-card-role \{ color: var\(--rules-strategy-blue\); \}/);
  assert.match(rulesStyles, /\.wiki-card-role \{[^}]*font: 700 12px\/1\.1/);
  assert.match(rules, /const renderAiContent = \(paragraph: HTMLElement, content: string\)/);
  assert.match(rules, /parseAiContent\(content\)/);
  assert.match(rules, /资料库中没有明确记载.*\[规则书\]\(\/investigation-delve-boardgame\/rules\)/);
  assert.match(aiServer, /const OPENCODE_URL = "https:\/\/opencode\.ai\/zen\/v1\/chat\/completions"/);
  assert.match(aiServer, /const OPENCODE_MODEL = "deepseek-v4-pro"/);
  assert.match(aiServer, /const OPENROUTER_URL = "https:\/\/openrouter\.ai\/api\/v1\/chat\/completions"/);
  assert.match(aiServer, /const OPENROUTER_MODEL = "stealth\/ox-alpha"/);
  assert.match(aiServer, /const OPENROUTER_FALLBACK_MODEL = "nvidia\/nemotron-3-super-120b-a12b:free"/);
  assert.match(aiServer, /process\.env\.OPENCODE_API_KEY/);
  assert.match(aiServer, /process\.env\.OPENROUTER_API_KEY/);
  assert.match(aiServer, /const OPENCODE_TIMEOUT_MS = 20_000/);
  assert.match(aiServer, /falling back to \$\{nextProvider\.name\}/);
  assert.match(aiServer, /max_tokens: 768/);
  assert.match(aiServer, /reasoning: \{ effort: "none", exclude: true \}/);
  assert.doesNotMatch(aiServer, /provider\.name === "OpenRouter" \? \{ reasoning:/);
  assert.match(aiServer, /const FINAL_OPEN_TAG = "<answer>"/);
  assert.match(aiServer, /reasoning_content/);
  assert.match(aiServer, /extractFinalAnswer/);
  assert.match(aiServer, /最终输出只能是对用户当前问题的直接回答/);
  assert.match(aiServer, /最终输出永远只使用用户输入的语言/);
  assert.doesNotMatch(rules, /开始提问/);
  assert.match(rules, /THE ANOMALY/);
  assert.match(rules, /调查异常环境，<br \/><em>谨慎追寻真相。<\/em>/);
});

test("source exposes the Ball Maze detail page and route", async () => {
  const source = await readFile(new URL("../src/ball-maze.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../src/ball-maze.css", import.meta.url), "utf8");
  const main = await readFile(new URL("../src/main.ts", import.meta.url), "utf8");
  const vercel = await readFile(new URL("../vercel.json", import.meta.url), "utf8");
  assert.match(source, /bootBallMazePage/);
  assert.match(source, /旋转世界，<br \/><em>让重力带路。/);
  assert.match(source, /data-ball-filter/);
  assert.match(source, /Steam Workshop/);
  assert.match(source, /class="bm-world-grid"/);
  assert.match(styles, /\.ball-maze-page/);
  assert.match(styles, /\.bm-reveal\.is-visible/);
  assert.match(main, /href="\/ball-maze"/);
  assert.match(main, /bootBallMazePage/);
  assert.match(vercel, /\/ball-maze\/:path\*/);
});
